repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
        language_version: python3
      - id: check-merge-conflict
      - id: name-tests-test
        exclude: tests/(common.py|util.py|(helpers|integration/factories)/(.+).py)
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.13.0
    hooks:
    - id: reorder-python-imports
      args:
        - --py3-plus
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy
